[package]
name = "ck3oop-core-rs"
version = "0.0.0"
edition = "2021"
authors = ["bukowa"]
repository = "https://github.com/bukowa/ck3oop"
keywords = ["ck3oop"]
license = "MIT"
homepage = "https://github.com/bukowa/ck3oop"

[dependencies]
