name: "Rust: Publish Crate"

on:

  workflow_dispatch:
    inputs:
      package:
        type: string
        description: 'Package to publish'
        required: true
        default: 'ck3oop-core-rs'
      tag:
        type: string
        description: 'Tag to publish'
        required: true
    secrets:
      RUST_CRATES_TOKEN:
        description: 'Token for publishing Rust crates'
        required: true

  workflow_call:
    inputs:
      package:
        type: string
        description: 'Package to publish'
        required: true
        default: 'ck3oop-core-rs'
      tag:
        type: string
        description: 'Tag to publish'
        required: true
    secrets:
      RUST_CRATES_TOKEN:
        description: 'Token for publishing Rust crates'
        required: true

jobs:

  publish-crates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: ${{ inputs.tag }}
          fetch-tags: true

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17 # v1
        with:
          toolchain: stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true

      - name: Publish
        run: |
          cargo login ${{ secrets.RUST_CRATES_TOKEN }}
          cargo publish -p ${{ inputs.package }}
