name: "Tauri: Publish Artifacts"

on:
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: 'ID of the release to publish'
        required: true
      tag:
        type: string
        description: 'Tag of the release to publish'
        required: true
  workflow_call:
    inputs:
      id:
        type: string
        description: 'ID of the release to publish'
        required: true
      tag:
        type: string
        description: 'Tag of the release to publish'
        required: true
jobs:

  publish-tauri:
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          #          - platform: 'macos-latest' # for Arm based macs (M1 and above).
          #            args: '--target aarch64-apple-darwin'
          #          - platform: 'macos-latest' # for Intel based macs.
          #            args: '--target x86_64-apple-darwin'
          #          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
          #            args: ''
          - platform: 'windows-latest'
            args: ''

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 22.2.0

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2
        with:
          cache-all-crates: true

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: Install frontend dependencies
        run: |
          npm install --loglevel verbose

      - name: Build workspace packages
        run: |
          npm run build

      - uses: tauri-apps/tauri-action@b1dc93b31afa36b1247a7a5f55c2dffbdc70dd05 # v0.5.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          includeDebug: true
          tagName: ${{ inputs.tag }}
          releaseId: ${{ inputs.id }}
          tauriScript: npm run --workspace ck3oop-ui tauri
          args: ${{ matrix.args }}
